module WERB
  class PageGenerator
    @doc_name: String

    @root_name: String

    @el_name_prefix: String

    TEMPLATE: untyped

    def initialize: (String doc_name, String root_name, String el_name_prefix) -> void

    def generate_html_page: (String input) -> String
  end
end
