module WERB
  class Templater
    @doc_name: String

    @root_name: String

    @el_name_prefix: String

    TEMPLATE: String

    def initialize: (String doc_name, String root_name, String el_name_prefix) -> void

    def generate: (String input) -> String
  end

  class IIFETemplater < Templater
    TEMPLATE: String
  end

  class UMDTemplater < Templater
    TEMPLATE: String
  end
end
