module WERB
  class Templater
    @viewmodel_name: String

    @root_name: String

    @el_name_prefix: String

    TEMPLATE: String

    def initialize: (String filename, String root_name) -> void

    def generate: (String input) -> String
  end

  class IIFETemplater < Templater
    TEMPLATE: String
  end

  class UMDTemplater < Templater
    TEMPLATE: String
  end
end
