module WERB
  class DomElem
    class ERB end
    class Container end
    class Code end
    class Creator end
    class Str end
  end

  type dom_elem = DomElem::Str | DomElem::ERB | DomElem::Code | DomElem::Container | DomElem::Creator
  type raw_ast_node = String | untyped
end
