require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
  - 'werb.gemspec'

Metrics/MethodLength:
  Max: 15

Layout/FirstArgumentIndentation:
  Enabled: true
  Exclude:
    - 'spec/*'

Style/RedundantPercentQ:
  Enabled: true
  Exclude:
    - 'spec/werb/transpiler_spec.rb'

RSpec/ExampleLength:
  Enabled: false
