module WERB
  VERSION: String

  class Error < StandardError
  end

  class PatternMatchError < Error
  end

  class EmptyFrameError < Error
    @message: String

    def initialize: (?::String message) -> void
  end
end
